name: CI Test

on: [push, pull_request]

jobs:

  test-all:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        env:
            DEBIAN_FRONTEND: noninteractive  
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y libgtest-dev libgmock-dev
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: "3.16.x"
      - name: Compile Unit Tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          rm -rf ./*
          cmake -DCMAKE_BUILD_TYPE=Debug ../test
          make -j4
      - name: Run Unit Tests
        working-directory: build
        run: $GITHUB_WORKSPACE/build/safe_callback_test

