name: CI Test

on: [push, pull_request]

jobs:

  test-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: "3.21.x"
      - name: Compile Unit Tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          rm -rf ./*
          cmake -DCMAKE_BUILD_TYPE=Debug ../test
          make -j4
      - name: Run Unit Tests
        working-directory: build
        run: $GITHUB_WORKSPACE/build/safe_callback_test

  test-macos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [macos-11.0]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: "3.21.x"
      - name: Compile Unit Tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          rm -rf ./*
          cmake -DCMAKE_BUILD_TYPE=Debug ../test
          make -j4
      - name: Run Unit Tests
        working-directory: build
        run: $GITHUB_WORKSPACE/build/safe_callback_test

  test-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [windows-2019]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: "3.21.x"
      - name: Compile Unit Tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          rm -rf ./*
          cmake -DCMAKE_BUILD_TYPE=Debug ../test
          cmake --build $GITHUB_WORKSPACE/build --config Debug
      - name: Run Unit Tests
        working-directory: build
        run: $GITHUB_WORKSPACE/build/Debug/safe_callback_test.exe